name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cargo generate
      run: cargo install cargo-generate
    - name: Run Build
      run: RUST_BACKTRACE=1 cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose
    - name: fmt
      run: cargo fmt