name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cargo generate
      run: cargo install cargo-generate
    - name : generate script
      run : cargo generate --init fuellabs/sway templates/sway-test-rs --name token_deployer  --force
    - name : Run Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name : fmt
      run: cargp fmt 
